### ISSUE TITLE
Some examples on CodeSandbox not working anymore since react-curtains @1.0.8

### ISSUE THREAD

**Issue by theosenoussaoui** [martinlaxenaire/react-curtains#3]
Hey, thanks for the port of curtainsjs to REact, using it now and I've learned quite a lot about WebGL already<
Some of the demos you've done on CodeSandbox aren't worrking anymore, and if I change the version back to 1,0.6, thne it magically works again. For example [this one](https://codesandbox.io/s/1g5zj) doesn't work unless I downgrade the package version.

Peace and thank you for your work. :v:

**Comment by martinlaxenaire** [comment]
Hey @theosenoussaoui,

You're right indeed, I've forgotten to patch a few things on react-curtains following curtains.js v8.0 release, especially the `FXAAPass` component. This should be fixed with v1.0.9: b6814403736fc638beb6b87ef29996fabf12f286

Also in your first version you were asking for a port of the scrolling wheel example, so here is a basic port (no touch support tho): https://codesandbox.io/s/react-curtains-rotating-planes-ylp29

Cheers,

**Comment by theosenoussaoui** [comment]
Thanks for the quick answer and the fix. I managed to get the port working (this is why I've deleted it) but thank you anyway.
