### ISSUE TITLE
Could not find a declaration file for module 'react-curtains'

### ISSUE THREAD

**Issue by Forpee** [martinlaxenaire/react-curtains#9]
This is the issue i am experiencing in vs code when using next.js

**Comment by martinlaxenaire** [comment]
Hey @Forpee,

Altho you're not mentioning it, I guess you're using Typescript.
I'm no TS user myself, but I think you should have a look at those Stack Overflow answers:
- https://stackoverflow.com/a/50516783/13354068
- https://stackoverflow.com/a/58750175/13354068

Let me know if that works.

Cheers,

**Comment by Forpee** [comment]
Its odd because I'm not actually using typescript that's why this is confusing. I think it might have to do with next.js ssr

**Comment by martinlaxenaire** [comment]
Hey @Forpee,

Could you provide more details on your next setup and the error you're getting?

Considering this issue and #10, I've made a quick test setting up a next.js app with:

`npm init next-app nextjs-blog` and then `npm install react-curtains`

And here is the content of my `_app.js` file:

```jsx
import {useState, useEffect} from 'react';

import '../styles/globals.css';
import {Curtains, Plane} from 'react-curtains';

const basicVs = `
    precision mediump float;
    
    attribute vec3 aVertexPosition;
    attribute vec2 aTextureCoord;
    
    uniform mat4 uMVMatrix;
    uniform mat4 uPMatrix;
        
    varying vec3 vVertexPosition;
    varying vec2 vTextureCoord;
    
    void main() {
        gl_Position = uPMatrix * uMVMatrix * vec4(aVertexPosition, 1.0);
        
        // varyings
        vVertexPosition = aVertexPosition;
        vTextureCoord = aTextureCoord;
    }
`;


const basicFs = `
    precision mediump float;

    varying vec3 vVertexPosition;
    varying vec2 vTextureCoord;
    
    void main() {        
        gl_FragColor = vec4(1.0, 0.0, 0.0, 1.0);
    }
`;

function BasicPlane({children}) {
    return (
        <Plane
            className="BasicPlane"

            // plane init parameters
            vertexShader={basicVs}
            fragmentShader={basicFs}
        >
            {children}
        </Plane>
)
}

function MyApp({ Component, pageProps }) {
    const [showChild, setShowChild] = useState(false);

    // Wait until after client-side hydration to show
    useEffect(() => {
        setShowChild(true);
    }, []);

    if (!showChild) {
        // You can show some kind of placeholder UI here
        return null;
    }

    return <Curtains><BasicPlane /><Component {...pageProps} /></Curtains>
}

export default MyApp
``` 

Everything is working fine, I don't get any error.

Cheers,

**Comment by Forpee** [comment]
@martinlaxenaire 
Thanks so much man! I  started a new project, used your code and got it to work...Secondly
just to clarify the message I was getting in vscode 
was when I import react-curtains, and the import line of code then has 3 dots by it... so when you hover over the three dots this message pops up
![Screenshot 2021-04-14 06 31 26](https://user-images.githubusercontent.com/59589957/114654790-2bbd3580-9ceb-11eb-9929-2127996ab95a.png)

**Comment by martinlaxenaire** [comment]
Hey @Forpee, 

this definitely looks like one of those typescript error I was referring to in the first answer. You might want to try one of these solutions.
Maybe you've created your next.js project using typescript by mistake, or you've misconfigured your linter, I don't know. Either way, one of the fix mentioned earlier should work.

Cheers,

**Comment by rsodre** [comment]
@martinlaxenaire, I'm following your pattern for next.js, but I find it only works when `Curtains` and `Plane` are on the same component, like `MyApp` above. If `Curtain` is on my main App component and `Plane` way down the line, I can see curtains.js is started on the console (curtains.js - v8.1.0), but when the plane is rendered, I get the error `Plane: Unable to create a Plane because the Renderer WebGL context is not defined`.

The curtains-canvas div is created, covering the viewport, but the webgl canvas is not inside it. Should I add a dummy `Plane` after `Curtains`? I don't want any shader covering the whole viewport, just over profile pictures on different places inside my page.

I'm certain `Curtains` is instantiated after the page loads.

**update**: By adding a simple plane right after the `Curtains` on my main app component, the canvas is created, and this plane is displayed, and the WebGL context error is gone. But the other ones down the hierarchy (the ones that really matter), do not display....

**Comment by martinlaxenaire** [comment]
Hey @rsodre,

It's hard to tell you what can go wrong without any code example.
I've set up a real quick dummy example of react-curtains + nextjs here (it just draws a red plane on the homepage): https://codesandbox.io/s/react-curtains-nextjs-basic-example-q3774j

Hope that helps.

Cheers,

**Comment by rsodre** [comment]
Hey martin,

I tried to reproduce my problem over your example, but couldn't.
https://codesandbox.io/s/react-curtains-nextjs-basic-example-forked-13t878

But I found others....

When you open and close planes on my example, the plane position is sometimes not updated. Example (please follow the plane order): Open planes 1, 2, 3. Then close 1, 2, 3. Then open 3, 2, 1.

Also, on the terminal I see a warning that I see all the time here:

```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
```

**Comment by martinlaxenaire** [comment]
Hey @rsodre,

 
> When you open and close planes on my example, the plane position is sometimes not updated. Example (please follow the plane order): Open planes 1, 2, 3. Then close 1, 2, 3. Then open 3, 2, 1.


This is not a bug but rather a misunderstanding of how the library works.
The planes that you've already created cannot "know" when you dynamically change the DOM. This is up to you to handle that by using the planes `updatePosition()` method.

The easiest way to do that would be to add this:

```javascript
useCurtains(
  (curtains) => {
    curtains.planes.forEach((plane) => {
      plane.updatePosition();
    });
  },
  [plane1, plane2, plane3]
);
```

See: https://codesandbox.io/s/react-curtains-nextjs-basic-example-forked-itkdm0?file=/pages/index.js:320-478

However this is not really optimised, especially if you have a large number of planes.


> Also, on the terminal I see a warning that I see all the time here:
> 
> ```
> Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
> ```

This is just a warning letting you know that some of the code will be run only on the client-side, which is fine because there's no point in running webgl on the server anyway.

I could however update the code to use `useEffect` instead.

Anyway, if you have any more questions/issues you might want to open a new issue because this has nothing to do with the original topic here.

Cheers,

**Comment by ventoline** [comment]
> Hey @Forpee,
> 
> Altho you're not mentioning it, I guess you're using Typescript. I'm no TS user myself, but I think you should have a look at those Stack Overflow answers:
> 
> * https://stackoverflow.com/a/50516783/13354068
> * https://stackoverflow.com/a/58750175/13354068
> 
> Let me know if that works.
> 
> Cheers,

Is there an example using typescript? I found a workaround to import the lib, but encounter now more issues. 


**Server Error
TypeError: Cannot read properties of undefined (reading 'curtains')**

```
useCurtains(
   (curtains) => {
```
